import moment from "moment";

export const MESSAGE = {
  LOADING: {
    title: `Данные обрабатываются..`,
    text: `Пожалуйста, подождите..`,
  },
};

export const FLIGHTS = [
  {
    id: `1`,
    price: `13 400`,
    airCompanyLogo: `s7logo`,
    airCompanyName: `Логотип авиакомпании s7`,
    departurePont: `MOW`,
    directDepurtureTime: moment(`2020-11-20 10:45`, `YYYY-MM-DD HH:mm`),
    arrivingPont: `Hkt`,
    directArrivingTime: moment(`2020-11-21 08:00 `, `YYYY-MM-DD HH:mm`),
    directTransfersAmount: `2`,
    directTransferPoint: `HKG, JNB`,
    returnDepurtureTime: moment(`2020-11-30 11:20`, `YYYY-MM-DD HH:mm`),
    returnArrivingTime: moment(`2020-12-01 00:55 `, `YYYY-MM-DD HH:mm`),
    returnTransfersAmount: `1`,
    returnTransferPoint: `HKG`,
    returnFlightDuration: `10`,
    directFlightDuration: `21`,
  },
  {
    id: `2`,
    price: `24 300`,
    airCompanyLogo: `s7logo`,
    airCompanyName: `Логотип авиакомпании s7`,
    departurePont: `MOW`,
    directDepurtureTime: moment(`2020-11-20 16:25`, `YYYY-MM-DD HH:mm`),
    arrivingPont: `Hkt`,
    directArrivingTime: moment(`2020-11-21 14:00 `, `YYYY-MM-DD HH:mm`),
    directTransfersAmount: `2`,
    directTransferPoint: `HKG, JNB`,
    returnDepurtureTime: moment(`2020-11-30 16:50`, `YYYY-MM-DD HH:mm`),
    returnArrivingTime: moment(`2020-12-01 14:00 `, `YYYY-MM-DD HH:mm`),
    returnTransfersAmount: `1`,
    returnTransferPoint: `HKG`,
    returnFlightDuration: `10`,
    directFlightDuration: `21`,
  },
  {
    id: `3`,
    price: `16 600`,
    airCompanyLogo: `turkish`,
    airCompanyName: `Логотип авиакомпании TurkishAirlines`,
    departurePont: `MOW`,
    directDepurtureTime: moment(`2020-11-20 04:25`, `YYYY-MM-DD HH:mm`),
    arrivingPont: `Hkt`,
    directArrivingTime: moment(`2020-11-21 17:00 `, `YYYY-MM-DD HH:mm`),
    directTransfersAmount: `3`,
    directTransferPoint: `HKG, JNB, IST`,
    returnDepurtureTime: moment(`2020-11-30 15:50`, `YYYY-MM-DD HH:mm`),
    returnArrivingTime: moment(`2020-12-01 14:00 `, `YYYY-MM-DD HH:mm`),
    returnTransfersAmount: `1`,
    returnTransferPoint: `HKG`,
    returnFlightDuration: `10`,
    directFlightDuration: `21`,
  },
  {
    id: `4`,
    price: `30 700`,
    airCompanyLogo: `s7logo`,
    airCompanyName: `Логотип авиакомпании s7`,
    departurePont: `MOW`,
    directDepurtureTime: moment(`2020-11-20 16:10`, `YYYY-MM-DD HH:mm`),
    arrivingPont: `Hkt`,
    directArrivingTime: moment(`2020-11-21 07:40 `, `YYYY-MM-DD HH:mm`),
    directTransfersAmount: `0`,
    directTransferPoint: ``,
    returnDepurtureTime: moment(`2020-11-30 02:20`, `YYYY-MM-DD HH:mm`),
    returnArrivingTime: moment(`2020-12-01 11:30 `, `YYYY-MM-DD HH:mm`),
    returnTransfersAmount: `0`,
    returnTransferPoint: `0`,
    returnFlightDuration: `10`,
    directFlightDuration: `21`,
  },
];
